Hero section
unreal998/libertydev-fe pull request #5
Opened 2024-02-22 19:32 UTC by RomchikSt

Trello: https://trello.com/c/d0Ru6rx7/3-hero-section

https://github.com/unreal998/libertydev-fe/assets/140477189/ef8619f6-2b17-4b55-88f0-fe1e825ab796

2024-02-24 18:04 UTC, unreal998 requested changes

2024-02-24 18:04 UTC, unreal998 commented on src/modules/homePage/components/DotsAnimation.tsx
> +        }}
does it base particles animation configuration?, can we move it in a separate config ?

2024-02-24 18:04 UTC, unreal998 commented on src/modules/homePage/sections/Hero.tsx
> +function Hero() {
use the same code style for all components `const Hero = () => {}`

2024-02-24 18:05 UTC, unreal998 commented
use the same branch naming pattern "feature/changesTitle" or "fix/changesTitle"

2024-02-24 20:51 UTC, RomchikSt commented on package.json
> +  "name": "liberty",
done

2024-02-24 20:53 UTC, RomchikSt commented on src/main.tsx
> -import React from 'react'
It's standard default naming in Vite. if U want I can rename

2024-02-24 20:56 UTC, RomchikSt commented on src/modules/homePage/components/DotsAnimation.tsx
> +        }}
I don't think it`s needed because it use once and that's why I created one component and write it all there

2024-02-24 20:59 UTC, RomchikSt commented on src/modules/homePage/sections/Hero.tsx
> +function Hero() {
done

2024-02-25 20:55 UTC, unreal998 approved these changes

2024-02-25 20:56 UTC, merged